CREATE EXTENSION IF NOT EXISTS vector;

CREATE TABLE IF NOT EXISTS search_sessions (
  id UUID PRIMARY KEY,
  query TEXT NOT NULL,
  mode TEXT NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS feedback (
  id BIGSERIAL PRIMARY KEY,
  session_id UUID,
  rating SMALLINT,
  comment TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
